from numpy import array 
TYPE_of_MODEL= 'HM' #'TVHM'
WINDOW='rect' #'hanning'
StationaryNoiseRemove = False # True
ADAPT_THR =  False
MAP_ESTIMATION = False # True
ENTROPY =  True
SIL_ENG = True 
NUMBER_OF_HARMONICS = 7
NUM_BASES_FUN = 5
ENTROPY_THR = 0.85  
HAM_WND = 25
WINDOW_LENGTH_StationaryNoise = 100
localDistHC_THR = 400
DEFAULT_FRAME_RATE = 0.01
DEFAULT_FRAME_DUR = 0.025
F0_MIN = 70 # Minimum possible F0 value
F0_RES = 1 # Frequency resolution 
F0_MAX = 400 # Maxmum possible F0 value
SIL_THRESHOLD = -50
VUV_TRANSITION = array([[.9, .1] , [.2, .8]]) # fixed transition probabilities
TinvMatDir = 'src/TinvMat/'
MIN_UNVOICED_DUR = 0.030
MAX_UNVOICED_DUR = 0.150
eps = np.finfo(float).eps
LAMBDA_REG=1 # for shimmer
UV_LOW_CLAMP = -100
UV_HI_CLAMP = 0
SIGMA_TRANS = 2 # pitch tracking
VU_THRESHOLD = 1.25   # the threshold must be optimized according to the noise level
